context:
  version: 1.0.8

package:
  name: bzip2
  version: ${{ version }}

source:
  url: https://sourceware.org/pub/bzip2/bzip2-${{ version }}.tar.gz
  sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - make
  run_exports:
    - ${{ pin_subpackage('bzip2') }}
