[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "build-feedstock"
platforms = ["osx-arm64"]
preview = ["pixi-build"]
version = "0.1.0"

[workspace.build-variants]
python_min = ["3.9"]

[dependencies]
pytest-order = { git = "https://github.com/conda-forge/pytest-order-feedstock", subdirectory = "recipe/" }
